/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Jpegoptim
 #	author : miyako
 #	2016/04/29
 #
 # --------------------------------------------------------------------------------*/

#include "jpeglib.h"

#define JPEG_STRIP_XMP 1
#define JPEG_STRIP_ICC 2
#define JPEG_STRIP_IPTC 4
#define JPEG_STRIP_EXIF 8
#define JPEG_STRIP_COM 16

struct my_error_mgr {
	struct jpeg_error_mgr pub;
	jmp_buf setjmp_buffer;
	int     jump_set;
};
typedef struct my_error_mgr * my_error_ptr;

typedef struct {
	struct jpeg_destination_mgr pub; /* public fields */
	
	unsigned char **buf_ptr;
	size_t *bufsize_ptr;
	size_t incsize;
	
	unsigned char *buf;
	size_t bufsize;
	
} jpeg_memory_destination_mgr;

typedef jpeg_memory_destination_mgr* jpeg_memory_destination_ptr;

// --- Jpegoptim
void Jpegoptim(sLONG_PTR *pResult, PackagePtr pParams);

#define EXIF_JPEG_MARKER   JPEG_APP0+1
#define EXIF_IDENT_STRING  "Exif\000\000"
#define EXIF_IDENT_STRING_SIZE 6

#define IPTC_JPEG_MARKER   JPEG_APP0+13

#define ICC_JPEG_MARKER   JPEG_APP0+2
#define ICC_IDENT_STRING  "ICC_PROFILE\0"
#define ICC_IDENT_STRING_SIZE 12

#define XMP_JPEG_MARKER   JPEG_APP0+1
#define XMP_IDENT_STRING  "http://ns.adobe.com/xap/1.0/\000"
#define XMP_IDENT_STRING_SIZE 29